services:

  postgres:
    image: postgres:16

    container_name: medical-postgres

    environment:
      POSTGRES_DB: medical_scheduling
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4

    container_name: medical-pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    depends_on:
      - postgres

  redis:
    image: redis:7

    container_name: medical-redis

    ports:
      - "6379:6379"

  webapi:
    build:
      context: ..
      dockerfile: src/MedicalScheduling.Presentation/WebAPI/Dockerfile
    container_name: medical-webapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=medical_scheduling;Username=postgres;Password=postgres
      ConnectionStrings__Redis: redis:6379
    ports:
      - "5263:8080"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ../src/MedicalScheduling.Presentation/Frontend
      dockerfile: Dockerfile
    container_name: medical-frontend
    ports:
      - "5173:80"
    depends_on:
      - webapi
