services:

  postgres-test:
    image: postgres:16

    container_name: medical-postgres-test

    environment:
      POSTGRES_DB: medical_scheduling_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    restart: always

  pgadmin-test:
    image: dpage/pgadmin4

    container_name: medical-pgadmin-test

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5051:80"

    depends_on:
      - postgres-test

    restart: always

  redis-test:
    image: redis:7

    container_name: medical-redis-test

    ports:
      - "6380:6379"

    restart: always
